// src/lib/components/common/Footer.svelte
<script lang="ts">
	import LogoLinkSlot from '../assets/slots/LogoLinkSlot.svelte';
	import Github from '../assets/svg/Github.svelte';
	import LinkedIn from '../assets/svg/LinkedIn.svelte';
	import TwitterX from '../assets/svg/TwitterX.svelte';
	import Youtube from '../assets/svg/Youtube.svelte';
</script>

<footer class="w-full flex items-center justify-between">
	<p class="text-sm">&copy; 2024 Srivarshan Geetha</p>
	<div class="flex">
		<LogoLinkSlot link="https://github.com/sri-varshan14">
			<Github cssClasses="social_link" />
		</LogoLinkSlot>
		<LogoLinkSlot link="https://twitter.com/Sri4574">
			<TwitterX cssClasses="social_link" />
		</LogoLinkSlot>
		<LogoLinkSlot link="">
			<LinkedIn cssClasses="social_link" />
		</LogoLinkSlot>
		<LogoLinkSlot link="https://www.youtube.com/@sri-varshan14">
			<Youtube cssClasses="social_link" />
		</LogoLinkSlot>
	</div>
</footer>

// src/components/common/Footer.tsx
import Link from "next/link";
import ArrowUpSVG from "../svg/ArrowUpSVG";
import LogoSVG from "../svg/LogoSVG";

const Footer = () => {
    return (
        <footer className="pl-14 py-10">
            <div className="h-[2px] bg-base-content px-8 my-8"></div>
            <div className="flex px-8 items-center justify-between ">
                <p className="font-semibold">Copyright &copy; 2024 Srivarshan</p>
                <LogoSVG cssClasses="w-10 fill-base-content" />
                <Link href="#">
                    <span className="flex items-center justify-center">
                        <p className="font-bold">Back to Top</p>
                        <ArrowUpSVG cssClasses="w-6 stroke-base-content" />
                    </span>
                </Link>
            </div>
        </footer>
    )
}

export default Footer;
